version: "3"

services:
  back_app:
    restart: always
    build: .
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - local-nest-mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  local-nest-mongodata: {}
